name: Release
on:
    push:
        tags: ['*']
env:
  GOPRIVATE: github.com/mayye4ka
  USER: ${{ github.actor }}
  TOKEN: ${{ secrets.TOKEN_SECRET }}
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - name: Configure git for private modules
        run: git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: make build
      - name: Test
        run: make test
  release-docker:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to ghcr
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.TOKEN_SECRET}}
      - name: Build image
        run: docker build --tag ghcr.io/mayye4ka/pinder:${{ github.ref_name }} --build-arg USER=${USER},TOKEN=${TOKEN} .
      - name: Push image
        run: docker push ghcr.io/mayye4ka/pinder:${{ github.ref_name }}