name: Unit tests
on:
    push:
        branches: ['*']
env:
  GOPRIVATE: github.com/mayye4ka
  USER: ${{ github.actor }}
  TOKEN: ${{ github.token }}
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - name: echo1
        run: echo "${USER}"
      - name: echo2
        run: echo "${#TOKEN}"
      - name: echo3
        run: go env GOPRIVATE
      - name: Configure git for private repos
        run: git config --global url."https://${USER}:${TOKEN_SECRET}@github.com/".insteadOf "https://github.com/"
      - name: List config
        run: git config --global --list
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: make build
      - name: Test
        run: make test