name: Unit tests
on:
    push:
        branches: ['*']
env:
  GOPRIVATE: github.com/mayye4ka
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://mayye4ka:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: make build
      - name: Test
        run: make test